apiVersion: v1
kind: ConfigMap
metadata:
  name: express-config
  namespace: td-mediatheque
data:
  NODE_ENV: production
  # MONGO_URI: mongodb://mongo:27017/td-mediatheque
  MONGO_URI: mongo-service.td-mediatheque.svc.cluster.local:27017/td-mediatheque
