name: Analyse SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    
  discord-notification:
    runs-on: ubuntu-latest
    needs: sonarqube
    if: always()
    steps:
      - name: Notify Discord (success)
        if: needs.sonarqube.result == 'success'
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"✅ Analyse SonarCloud **réussie** pour le commit \`${{ github.sha }}\` sur \`${{ github.ref }}\`.\nVoir le rapport : https://sonarcloud.io/project/overview?id=OoFlowoO34_Mediatheque-API\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord (failure)
        if: needs.sonarqube.result == 'failure'
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"❌ Analyse SonarCloud **échouée** pour le commit \`${{ github.sha }}\` sur \`${{ github.ref }}\`.\nVérifie les logs dans GitHub Actions.\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}

